# world
world: 'world'

# upon successful purchase of a chunk (recommendations: leave a space at the end)
successful purchase: 'You have successfully bought a chunk. '
coordinates of a chunk: 'Coordinates of a chunk: '
chunk amount: 'Total number of chunks in your city: '
tax: 'Taxes: '


# errors

# if player inventory is full
inventory is full: 'Your inventory is full'

# if this place is already occupied by these cities
taken chunk: 'on this chunk your city has already taken a place.'

# if player doesn't have city
player hasn't city: 'You are not a resident of any city.'

# if player has another city
player have another city: 'You are a resident of another city.'

# if the player doesn't place a flag next to the city
flag raised in the wrong place: 'Your city was not found in neighboring chunks, put a flag next to your city.'

# if the player places the flag next to other cities (at a distance of 3 chunks)
flag raised next to other city: 'There is a city near this chunk, set the flag at a distance of 3 chunks from other cities.'